### PR TITLE
Slides in Spanish delivered in Hackmeeting-ES 2018, La Invisible, Malaga on 2018-11-02

### PR DESCRIPTION
**Pull request by ilario**

### CODE REVIEW

**Comment by nicopace** [comment]
Hi Ilario,
Thanks for the submission.
My big question is if we should use this repo for all the documentation around, or just the manuals we are producing.
The repo was born as the placeholder for the librerouter documentation project...
There is no reason why not to mutate in that direction, but I think that it deserves a deeper conversation.
For now, I would encourage you to link to your repo from the libremesh.org site so we don't loose track of them.

**Comment by ilario** [comment]
My personal opinion is that we should archive somewhere also the rest of the documentation we have, for example we should have here the sources of @G10h4ck's and of @aparcar's theses. And this repository could serve the purpose.
But if we decide to not do this, that's ok for me.

**Comment by nicopace** [comment]
My concern right now is that as we are using this repo as the one that
translawiki is using for the translation platform, that it could get
messy with that.

If you want to guide the conversation please move it... if not, I can do
it once we have everything set up with translawiki and the IGF passed
(in 10 days aprox).

**Comment by ilario** [comment]
LOLOK, we could use the `lime-org` repository
https://github.com/libremesh/lime-org

**Comment by ilario** [comment]
> @nicopace @patogit let me know if lime-org is the right place and I will do a PR there
Ahem... @nicopace @patogit

**Comment by ilario** [comment]
Gosh I just realized this repository has moved to LibreRouter organization. This PR is mainly about LibreMesh (it cites also LibreRouter).
Does anyone have idea where should I send this PR?
Once decided we can move in the new locations also [these](https://github.com/libremesh/libre-mesh-tecnical-presentation-1h-reveal.js) [two](https://github.com/libremesh/libremap-talk-2013-is4cwn) presentations.

**Pull request closed without merging**
